/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAL.*;
import BL.*;
import java.io.File;
import java.nio.file.Path;
import javax.swing.JFileChooser;

/**
 *
 * @author Guszty
 */
public class AddAdvert extends javax.swing.JFrame {

    /**
     * Creates new form AddAdvert
     */
    
    String imageurl;
    String imagename;
    
    public AddAdvert() {
        
        initComponents();
        
        pretlabel.setVisible(false);
        zonalabel.setVisible(false);
        suprafatalabel.setVisible(false);
        prettextfield.setVisible(false);
        zonatextfield.setVisible(false);
        suprafatatextfield.setVisible(false);
        adaugaanuntbutton.setVisible(false);
        adaugapozabutton.setVisible(false);
        
        
        

    }

    
    public String geturl()
    {
        return imageurl;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titlutextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrieretextfield = new javax.swing.JTextPane();
        adaugapozabutton = new javax.swing.JButton();
        zonalabel = new javax.swing.JLabel();
        pretlabel = new javax.swing.JLabel();
        suprafatalabel = new javax.swing.JLabel();
        prettextfield = new javax.swing.JTextField();
        zonatextfield = new javax.swing.JTextField();
        suprafatatextfield = new javax.swing.JTextField();
        adaugaanuntbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Titlu:");

        jLabel2.setText("Categorie:");

        combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selectati...", "Anunt imobiliar", "Prestari servicii" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Descriere:");

        jScrollPane1.setViewportView(descrieretextfield);

        adaugapozabutton.setText("Adauga poza...");
        adaugapozabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugapozabuttonActionPerformed(evt);
            }
        });

        zonalabel.setText("Zona:");

        pretlabel.setText("Pret:");

        suprafatalabel.setText("Suprafata:");

        adaugaanuntbutton.setText("Adauga anunt");
        adaugaanuntbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugaanuntbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adaugaanuntbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adaugapozabutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(zonalabel)
                                .addComponent(jLabel3)
                                .addComponent(pretlabel)
                                .addComponent(suprafatalabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combobox, 0, 349, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(suprafatatextfield)
                            .addComponent(zonatextfield)
                            .addComponent(prettextfield)
                            .addComponent(titlutextfield))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titlutextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(adaugapozabutton)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pretlabel)
                    .addComponent(prettextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zonalabel)
                    .addComponent(zonatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suprafatalabel)
                    .addComponent(suprafatatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(adaugaanuntbutton)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
        
        String selectedadvert=combobox.getSelectedItem().toString();
        
        if(selectedadvert.equals("Selectati..."))
        {
            pretlabel.setVisible(false);
            zonalabel.setVisible(false);
            suprafatalabel.setVisible(false);
            prettextfield.setVisible(false);
            zonatextfield.setVisible(false);
            suprafatatextfield.setVisible(false);
            adaugaanuntbutton.setVisible(false);
            adaugapozabutton.setVisible(false);
           repaint();
        }
        
        
        if(selectedadvert.equals("Anunt imobiliar"))
        {
            pretlabel.setVisible(true);
            zonalabel.setVisible(true);
            suprafatalabel.setVisible(true);
            prettextfield.setVisible(true);
            zonatextfield.setVisible(true);
            suprafatatextfield.setVisible(true);
            adaugaanuntbutton.setVisible(true);
            adaugapozabutton.setVisible(true);
            repaint();
        }
        
        if(selectedadvert.equals("Prestari servicii"))
        {
            pretlabel.setText("Pret pe ora:");
            pretlabel.setVisible(true);
            prettextfield.setVisible(true);
            
            zonalabel.setVisible(false);        
            suprafatalabel.setVisible(false);
            zonatextfield.setVisible(false);
            suprafatatextfield.setVisible(false);
            adaugaanuntbutton.setVisible(false);
            adaugaanuntbutton.setVisible(true);
            adaugapozabutton.setVisible(true);
           repaint();
        }
    }//GEN-LAST:event_comboboxActionPerformed

    private void adaugapozabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugapozabuttonActionPerformed
        // TODO add your handling code here:
        
        
   
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
          File selectedFile = fileChooser.getSelectedFile();
          System.out.println(selectedFile.getName());
          System.out.println(fileChooser.getSelectedFile().getAbsolutePath());
          imageurl=fileChooser.getSelectedFile().getAbsolutePath();
          imagename=selectedFile.getName();
          
        }
      
    }//GEN-LAST:event_adaugapozabuttonActionPerformed

    private void adaugaanuntbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugaanuntbuttonActionPerformed
        // TODO add your handling code here:
        
        String selectedadvert=combobox.getSelectedItem().toString();
        AdvertBL advertbl=new AdvertBL();
        
        
        if(selectedadvert.equals("Anunt imobiliar"))
        {
            String title=titlutextfield.getText();
            String description=descrieretextfield.getText();
            double price=Double.valueOf(prettextfield.getText());
            String zone=zonatextfield.getText();
            double surface=Double.valueOf(suprafatatextfield.getText());
            
            
            //System.out.println("antetul: titlu:"+title+"\ndescription: "+description+"\nprice: "+price+"\nzone: "+zone+"\nsurface: "+surface+"\nurl: "+imageurl);
            
            
            advertbl.addImmobilierAdvert(title, description, imageurl, price, zone, surface,imagename);
            

        }
      
        //advertbl.addImmobilierAdvert("apartament", "3 camere", imageurl, 63000.0, "zorilor", 63.0);
        
        
        
        
        
    }//GEN-LAST:event_adaugaanuntbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adaugaanuntbutton;
    private javax.swing.JButton adaugapozabutton;
    private javax.swing.JComboBox combobox;
    private javax.swing.JTextPane descrieretextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pretlabel;
    private javax.swing.JTextField prettextfield;
    private javax.swing.JLabel suprafatalabel;
    private javax.swing.JTextField suprafatatextfield;
    private javax.swing.JTextField titlutextfield;
    private javax.swing.JLabel zonalabel;
    private javax.swing.JTextField zonatextfield;
    // End of variables declaration//GEN-END:variables
}
