/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BL.AdvertBL;
import OTHER.Advert;
import OTHER.ImmobilierAdvert;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guszty
 */
public class ViewAdverts extends javax.swing.JFrame {

    /**
     * Creates new form ViewAdvert
     */
    public ViewAdverts() {
        initComponents();
        drawall();
        
                
        table.addMouseListener(new MouseAdapter() 
        {
            public void mouseClicked(MouseEvent e) {
            int row = table.getSelectedRow();
            int col = table.getSelectedColumn();

            //System.out.println("row: "+row+" col: "+col);
            
            //new DisplayImmobilierAdvert().show();

            displayinformation(row,col);   
            
            
        }
        });
        
    }

    
        public void displayinformation(int row,int col)
    {
        String selectedtitle=(String) table.getModel().getValueAt(row,0);
        AdvertBL advertbl=new AdvertBL();
        ImmobilierAdvert advert=(ImmobilierAdvert)advertbl.getimmobilieradvert(selectedtitle);

        new DisplayImmobilierAdvert(advert).show();
        
    }
    
    
    public void drawall()
    {
        
               
        DefaultTableModel jtable = (DefaultTableModel) table.getModel();
        jtable.setNumRows(0); 
        table.setRowHeight(100);
        
                
        AdvertBL advertbl=new AdvertBL();
       
        ArrayList<Advert> adverts = advertbl.getalladverts();
       
        int numberofadverts= adverts.size();
        
        Advert advert=null;
        
        for(int i=0;i<numberofadverts;i++)
        {
            advert=adverts.get(i);
            
            System.out.println("url imagine: "+advert.geturl());
            
            jtable.addRow(new Object[]{advert.gettitle(),advert.getdescription(),""});
            ImageIcon icon = new ImageIcon(advert.geturl());
            table.getColumnModel().getColumn(2).setCellRenderer(new ImageRenderer());
            jtable.setValueAt(icon, i, 2);
        }
        
    }
    
    public void searchinadverts(String searchtext)
    {
 
        DefaultTableModel jtable = (DefaultTableModel) table.getModel();
        jtable.setNumRows(0); 
        table.setRowHeight(100);
        
                
        AdvertBL advertbl=new AdvertBL();
       
        ArrayList<Advert> adverts = advertbl.searchinadverts(searchtext);
       
        int numberofadverts= adverts.size();
        
        Advert advert=null;
        
        for(int i=0;i<numberofadverts;i++)
        {
            advert=adverts.get(i);
            
            System.out.println("url imagine: "+advert.geturl());
            
            jtable.addRow(new Object[]{advert.gettitle(),advert.getdescription(),""});
            ImageIcon icon = new ImageIcon(advert.geturl());
            table.getColumnModel().getColumn(2).setCellRenderer(new ImageRenderer());
            jtable.setValueAt(icon, i, 2);
        }
        
       
        this.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titlugettext = new javax.swing.JTextField();
        vizualizarebutton = new javax.swing.JButton();
        viewallbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Titlu:");

        vizualizarebutton.setText("Vizualizare");
        vizualizarebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizualizarebuttonActionPerformed(evt);
            }
        });

        viewallbutton.setText("View All");
        viewallbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallbuttonActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titlu", "Descriere", "Poza"
            }
        ));
        table.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(table);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(titlugettext, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vizualizarebutton)
                            .addGap(62, 62, 62)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewallbutton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titlugettext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vizualizarebutton))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewallbutton)
                    .addComponent(jButton1))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewallbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallbuttonActionPerformed
        // TODO add your handling code here:
        drawall();
        
    }//GEN-LAST:event_viewallbuttonActionPerformed

    private void vizualizarebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualizarebuttonActionPerformed
        // TODO add your handling code here:
        
        String titletext=titlugettext.getText();
        
        searchinadverts(titletext);
    }//GEN-LAST:event_vizualizarebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        table.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdverts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdverts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdverts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdverts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAdverts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable table;
    private javax.swing.JTextField titlugettext;
    private javax.swing.JButton viewallbutton;
    private javax.swing.JButton vizualizarebutton;
    // End of variables declaration//GEN-END:variables
}
